import type { Metadata } from "next";
import { roboto } from "./ui/fonts";
import "./globals.css";
import { Navbar } from "./ui/navbar";
import logo from "@/public/y-clipboard-logo.svg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Navbar logo={logo} />
        {children}
      </body>
    </html>
  );
}
